### ISSUE TITLE
Error while loading extension (Gnome 3.18)

### ISSUE THREAD

**Issue by illwieckz** [JuBan1/radeon-dpm-control#1]
Hey, thank you for writing that extension. I tried to load it but Gnome Tweak Tool said there is an error while loading the extension. Badly, I found nowhere any useful information to debug that. I'm not very aware with Gnome Shell extension writing, what I can do to fix the error?

**Comment by JuBan1** [comment]
I've fixed some issues with the enabling/disabling code so you could try again with a fresh clone (probably have to make uninstall, then make install).

Unfortunately I don't know much about GNOME extensions either. As far as I can see, there's almost no way of properly debugging them. An "error loading extension" is pretty much the only thing you get.

**Comment by illwieckz** [comment]
For your information, I found a way to print some log doing:

```
journalctl /usr/lib/gnome-session/gnome-session-binary -f -o cat
```

Perhaps the path is something else if you does not use Ubuntu/Debian.

If this path is wrong for you, just do a `journalctl -f | grep gnome-session` and look for the process number, then grep `ps` with that process number to find the real binary.

**Comment by illwieckz** [comment]
Oh sorry, I don't know why I missed that last commit… I'm trying it. :-)

**Comment by illwieckz** [comment]
it looks like it works
