### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by illwieckz** [JuBan1/radeon-dpm-control#2]
Hi, can you put a proper license in your project?

If you don't need something strong, you can use a very simple, permissive and laconic license like the [ISC one I use](https://raw.githubusercontent.com/illwieckz/dpm-query/master/COPYING.md), or [the one you prefer](http://choosealicense.com/).

Thanks.

**Comment by JuBan1** [comment]
Thanks for your additions. I'm quite new to all this Linux stuff and this has been very insightful. 

The license along with some other changes has been added.
