### ISSUE TITLE
Extension "radeon-dpm-control@s3rius" had error: SyntaxError: redeclaration of let gicon

### ISSUE THREAD

**Issue by i30817** [JuBan1/radeon-dpm-control#8]
This happens on a recent update of Ubuntu 18.04.1 LTS. Was working until yesterday.

**Comment by i30817** [comment]
Ok this was already fixed with a commit 11 months ago, but not on the gnome3 site apparently. I hacked around it by comparing this repository extension.js to the one i had locally. I have no idea why this was only error-ed out now.

**Comment by JuBan1** [comment]
Thanks for the report. It seems I forgot to update the extension on the Gnome site back then. I just did that and the new version is under review. Once that's done everyone should be able to get the proper version.
